model_name: dbmdz/bert-base-turkish-cased
output_dir: outputs/bert-turkish-cls
artifacts_dir: artifacts/bert-turkish-cls

seed: 42

data:
  train_file: data/processed/train.csv
  val_file: data/processed/val.csv
  test_file: data/processed/test.csv
  text_column: text
  label_column: label
  group_column: ""  # optional: for leakage control (same group kept in same split)

training:
  num_train_epochs: 5
  per_device_train_batch_size: 16
  per_device_eval_batch_size: 32
  gradient_accumulation_steps: 1
  learning_rate: 2.0e-5
  weight_decay: 0.01
  warmup_ratio: 0.1
  max_length: 128
  fp16: true
  save_total_limit: 2
  logging_steps: 50
  eval_strategy: epoch
  save_strategy: epoch
  metric_for_best_model: f1_macro
  greater_is_better: true
  label_smoothing_factor: 0.1
  early_stopping_patience: 2
  use_class_weights: true
  dropout_prob: 0.1
